# 16 ufunc

Universal functions operate elementwise on arrays. Examples include `np.add`, `np.subtract`, `np.multiply`, etc.

In [1]:
import numpy as np

## out=

In [2]:
a = np.array([1, 2, 3])
out = np.empty_like(a)
np.square(a, out=out)

array([1, 4, 9])

## where=

In [4]:
x = np.array([-1.0, 8.0, -7.0, 19.0, -5.0])
np.sqrt(x, where=x >= 0, out=np.zeros_like(x))

array([0.        , 2.82842712, 0.        , 4.35889894, 0.        ])

## .at

Unbuffered, in-place operation at specified indices.

In [9]:
a = np.array([1, 2, 3, 4])
np.negative.at(a, [0, 1, 1]) # a is modified in place, indices selects locations in a
a

array([-1,  2,  3,  4])

In [7]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1) # np.add.at(a, indices, values_to_add)
a

guess_a = np.array([2, 3, 5, 4])

assert np.all(guess_a == a)

Can specify multiple repeated indices.

In [8]:
a = np.zeros(5)
idx = np.array([1, 1, 1])

np.add.at(a, idx, 1)

guess_a = np.array([0, 3, 0, 0, 0])

assert np.all(guess_a == a)

In [12]:
x = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
labels = np.array([0, 1, 0])

out = np.zeros((2, 2))
np.add.at(out, labels, x) # iterates over x

# for i in range(len(labels)):
#     out[labels[i]] += x[i]

In [13]:
out

array([[6., 8.],
       [3., 4.]])

In [14]:
out = np.zeros((3, 4))

x = np.array([
    [ 1,  2,  3,  4],
    [10, 20, 30, 40],
    [ 5,  5,  5,  5],
    [ 7,  8,  9, 10],
])

idx = np.array([2, 0, 2, 1])
np.add.at(out, idx, x)

out_guess = np.array([
    [10, 20, 30, 40],
    [7, 8, 9, 10],
    [6, 7, 8, 9],
])

assert np.all(out_guess == out)