# 17 Transposing

## 2D Transpose

In [1]:
import numpy as np

In [3]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x.T # (2, 3) -> (3, 2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
x.strides

(24, 8)

In [5]:
x.shape

(2, 3)

In [6]:
x.transpose(1, 0)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
x.swapaxes(0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])